auto_discover: true

playlists:
  - name: "テスト"
    spotify:
      playlist_id: "1q7MQFhtr0yzVfs1DW3wUr"
    # apple_music:
    #   playlist_url: ""
    # amazon_music:
    #   playlist_url: ""

notification:
  email: "user@example.com"
  smtp_host: "smtp.gmail.com"
  smtp_port: 587

sync:
  cron: "0 3 * * *"
